# Generated by Django 4.2.18 on 2025-07-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='预订日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='配送日期'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('immediate', '立即购买'), ('booking', '预订')], default='immediate', max_length=20, verbose_name='订单类型'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='收件人姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='收件人电话'),
        ),
        migrations.AddField(
            model_name='order',
            name='special_requirements',
            field=models.TextField(blank=True, null=True, verbose_name='特殊要求'),
        ),
    ]
