# Generated by Django 5.2.4 on 2025-07-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='花卉名称')),
                ('usage', models.CharField(blank=True, max_length=255, null=True, verbose_name='用途')),
                ('season', models.CharField(blank=True, max_length=255, null=True, verbose_name='季节')),
                ('origin', models.CharField(blank=True, max_length=100, null=True, verbose_name='产地')),
                ('flower_language', models.CharField(blank=True, max_length=255, null=True, verbose_name='花语')),
                ('care_requirements', models.TextField(blank=True, null=True, verbose_name='养护要求')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='库存数量')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flowers/', verbose_name='图片')),
            ],
            options={
                'verbose_name': '花卉',
                'verbose_name_plural': '花卉',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='药品名称')),
                ('symptoms', models.TextField(verbose_name='适用病虫害症状')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
            },
        ),
    ]
