# Generated by Django 5.2.4 on 2025-07-24 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
