# Generated by Django 5.2.4 on 2025-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_delete_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='药品名称')),
                ('symptoms', models.TextField(verbose_name='适用病虫害症状')),
            ],
            options={
                'verbose_name': '药品',
                'verbose_name_plural': '药品',
            },
        ),
    ]
