# Generated by Django 4.2.18 on 2025-07-26 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_post_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='bouquet_type',
            field=models.CharField(choices=[('single', '单支花'), ('small', '小花束'), ('medium', '中花束'), ('large', '大花束'), ('luxury', '豪华花束')], default='single', max_length=20, verbose_name='花束类型'),
        ),
        migrations.AddField(
            model_name='flower',
            name='is_available_for_booking',
            field=models.BooleanField(default=True, verbose_name='可预订'),
        ),
        migrations.AddField(
            model_name='flower',
            name='size',
            field=models.CharField(choices=[('mini', '迷你型'), ('small', '小型'), ('medium', '中型'), ('large', '大型'), ('extra_large', '特大型')], default='medium', max_length=20, verbose_name='花束大小'),
        ),
    ]
