# Generated by Django 5.2.4 on 2025-07-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=10, verbose_name='余额'),
        ),
    ]
